### ISSUE TITLE
output.h5 and output_filtered.h5 files are identical

### ISSUE THREAD

**Issue by katiesaund** [broadinstitute/CellBender#138]
I recently installed and ran cellbender. Surprisingly, for all samples the resulting output.h5 and output_filtered.h5 files were identical. 99% of columns in the output files had entirely 0 counts. 

<img width="528" alt="image" src="https://user-images.githubusercontent.com/16493784/179095722-89a4c13f-a69e-4b77-80fe-0ee5b1d0b4d7.png">

The output plots for this sample are below: 
![unnamed](https://user-images.githubusercontent.com/16493784/179095905-a64e0fc8-85c4-4bad-b7b4-4392f46dd02b.png)

Why might the output.h5 and output_filtered.h5 files be identical? Does cellbender really think that all the droplets are non-empty? 

I ran cellbender using the default commands recommended on the [usage](https://cellbender.readthedocs.io/en/latest/usage/index.html) documentation page. Do you have any suggestions for how to improve the performance for these samples?

Thank you for your consideration!
-Katie

**Comment by sjfleming** [comment]
Hi @katiesaund ,

The "cell probability" plot is showing me that cellbender does think that lots of the droplets are empty.  Maybe around 7.5k droplets (plus or minus a few thousand) look like they have cells.  And then it looks like your R code shows that in fact 6766 cells were called by cellbender.

One thing I will say about the `output.h5` and `output_filtered.h5` files is that they are basically redundant.  Droplets determined to be "empty" by cellbender will have zero counts in the output (since an empty droplet is all noise, and the output has the noise removed).  So the count matrices are indeed identical.  The only difference is the shape of the count matrices (and how latent variable information is stored).  The empty droplets are included as columns in the `output.h5` but should be absent from the `output_filtered.h5`.  The only reason I output both is that for some people its more convenient to load one or the other downstream.

The reason so many columns are empty is that there are all 2.4 million droplet barcodes included in the count matrix, but only 6.7k cells.
