### ISSUE TITLE
Readthedocs broken

### ISSUE THREAD

**Issue by apredeus** [broadinstitute/CellBender#146]
Hi, 

I think something broke the readthedocs code. Looks strange now.

**Comment by sjfleming** [comment]
I agree, I have asked readthedocs about it, but have not heard back yet.  The docs used to look fine, but after a build by readthedocs about a month or two ago, all the css is broken.

I think I know how to fix this in the next commit, but I also think it's some kind of readthedocs bug, because it used to look fine, and there have been no changes.

**Comment by sjfleming** [comment]
Remove these lines
https://github.com/broadinstitute/CellBender/blob/cb2d209d5aedffe71e28947bc5b7859600aef64d/docs/source/conf.py#L67-L71

**Comment by sjfleming** [comment]
Should be all good now!

**Comment by sjfleming** [comment]
Closed by #238
