### ISSUE TITLE
Unable to save plot

### ISSUE THREAD

**Issue by williamwuyulu** [broadinstitute/CellBender#154]
Hi,

After some attempts, I was able to finish running the cellbender:remove-background program on the HPC cluster now.
However, in the final result file, I am missing the PDF file. I checked the log: it shows 
> cellbender:remove-background: Unable to save plot

I uploaded the full log, could please help me with what is causing this error to be reported?
[output.log](https://github.com/broadinstitute/CellBender/files/9528648/output.log)
[cellbender_A_v100_out.txt](https://github.com/broadinstitute/CellBender/files/9528649/cellbender_A_v100_out.txt)

Thank you very much for your help and time.

Best,

Peidong

**Comment by sjfleming** [comment]
Hi Peidong,

I should probably change how the error is reported in that case, since you cannot tell what went wrong... it is probably some issue with the installation of matplotlib.

If you want to dig into it and figure out what's wrong, you will need to change a few lines of the cellbender source code.

Try adding these lines of code
```python
import traceback
print(traceback.format_exc())
```
at line 766 of `dataset.py`
https://github.com/broadinstitute/CellBender/blob/cb2d209d5aedffe71e28947bc5b7859600aef64d/cellbender/remove_background/data/dataset.py#L766

Then run the workflow again, and you should see the full error message.  Hopefully that will give you an idea how to fix it.

**Comment by williamwuyulu** [comment]
Hi Stephen，
Thanks for the suggestion, based on your suggestion, I reinstalled matplotlib in my environment and after that, I reran the program and it worked！

Thanks so much for the help!

Best,

William
