### ISSUE TITLE
How to check which cells are removed after cellbender?

### ISSUE THREAD

**Issue by devenderarora** [broadinstitute/CellBender#158]
Dear Cellbender team,
I am using cellbender for my scRNA data. I am trying to understand at the gene level as well as at the cell level what is happening to data after cellbender. We found a number of cells removed but how can we identify which cells were removed? Also at the gene level, we were trying to understand the changes following the post: [https://github.com/broadinstitute/CellBender/issues/152#issuecomment-1255479940](https://github.com/broadinstitute/CellBender/issues/152#issuecomment-1255479940) we were not able to replicate until performing minor changes for example: 
## at compute the counts of each gene

adata.var['n_raw'] = np.array(adata.layers['raw'].sum(axis=0)).squeeze()
We changed the raw file name to 
**adata_raw**.var['n_raw'] = np.array(**adata_raw**.layers['raw'].sum(axis=0)).squeeze()

adata.var['n_cellbender'] = np.array(adata.layers['cellbender'].sum(axis=0)).squeeze()

Is these the right changes required in the code?

Also, the output followed by the script gave output with columns:

**ambient_expression** 	**feature_type** 	**genome** 	**gene_id** 	**n_cellbender** 	**n_cellbender_in_cells** 	**fraction_removed_from_cells**

Can you provide us with the documentation of these column names? And how can we check which cells were removed from cellbender analysis?

Thank you
Devender

**Comment by sjfleming** [comment]
Hi @devenderarora , actually I think the right change in the code might be to add `analyzed_barcodes_only=False` to the `anndata_from_h5()` function call.  (I just went back and edited my answer to #125 to include this)  Like this:

```python
import scanpy as sc
import numpy as np

# load data
adata_raw = sc.read_10x_h5('INPUT_FILE.h5')
adata = anndata_from_h5('CELLBENDER_OUTPUT_FILE.h5', analyzed_barcodes_only=False)
```

That way, the shapes of `adata` and `adata_raw` will match.  Then the following lines like 
```python
adata.layers['raw'] = adata_raw.X.copy()
```
and
```python
adata.var['n_raw'] = np.array(adata.layers['raw'].sum(axis=0)).squeeze()
```
should work, as well as what follows.

As for which cells are retained by cellbender and which are eliminated, one way to look at that would be:

```python
import scanpy as sc
import numpy as np

# load data
adata_raw = sc.read_10x_h5('INPUT_FILE.h5')
adata = anndata_from_h5('CELLBENDER_OUTPUT_FILE.h5', analyzed_barcodes_only=False)
```
and then something like
```python
[bc for bc in adata_raw.obs_names if (bc not in adata.obs_names)]
```
to see which barcodes are _not_ included in the cellbender filtered output.

**Comment by devenderarora** [comment]
Thank you for the quick response @sjfleming I am having specific queries about cell bender output:
When we ran cell bender we got two.h5 fiiles "raw" and "filter"

The raw files consist of a matrix:
AnnData object with n_obs × n_vars = 2590912 × 33538
    var: 'ambient_expression', 'feature_type', 'genome', 'gene_id'
    **uns**: 'barcode_indices_for_latents', 'contamination_fraction_params', 'fraction_data_used_for_testing', 'lambda_multiplier', 'latent_RT_efficiency', '**latent_cell_probability**', 'latent_gene_encoding', 'latent_scale', 'overdispersion_mean_and_scale', 'target_false_positive_rate', 'test_elbo', 'test_epoch', 'training_elbo_per_epoch'

Filtered matrix: 10960 × 33538
AnnData object with n_obs × n_vars = 10960 × 33538
    **obs**: 'latent_RT_efficiency', '**latent_cell_probability**', 'latent_scale'
    var: 'ambient_expression', 'feature_type', 'genome', 'gene_id'
    uns: 'contamination_fraction_params', 'fraction_data_used_for_testing', 'lambda_multiplier', 'overdispersion_mean_and_scale', 'target_false_positive_rate', 'test_elbo', 'test_epoch', 'training_elbo_per_epoch'
    obsm: 'latent_gene_encoding'

For [https://github.com/broadinstitute/CellBender/issues/152#issuecomment-1255479940](https://github.com/broadinstitute/CellBender/issues/152#issuecomment-1255479940)
cell_logic = (adata.obs['latent_cell_probability'] > 0.5)
KeyError: 'latent_cell_probability'
cell_logic = (adata.**uns**['latent_cell_probability'] > 0.5)
I am able to perform the same function

When I am looking into the gene data with:

adata.var.head()
There is no description for 
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/arora172/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/arora172/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



n_cellbender | n_raw_in_cells | n_cellbender_in_cells | fraction_removed
-- | -- | -- | --




</body>

</html>
May I know what these column means and how they have been calculated as well there is the last column with no name.

\n
For identifying cells
When I am trying to use:
adata_cells = adata[adata.obs['latent_cell_probability'] > 0.5].copy()
KeyError: 'latent_cell_probability'
or

adata_cells = adata[adata.**uns**['latent_cell_probability'] > 0.5].copy()
IndexError: Boolean index does not match AnnData\u2019s shape along this dimension. Boolean index has shape (20000,) while AnnData index has shape (2590912,).

Can you please help me with these concern issues with the cell bender?
I will be thankful to you.
Regards,
Devender

**Comment by sjfleming** [comment]
For `adata.var` descriptions:

- `n_cellbender`: This is the total number of counts of each gene in the cellbender output (`np.array(adata_cellbender.X.sum(axis=0)).squeeze()`)
- `n_raw_in_cells`: This is the total number of counts of each gene in the raw data, for cellbender-determined cells only (`np.array(adata.X[cell_logic].sum(axis=0)).squeeze()`)
- `n_cellbender_in_cells`: This is the total number of counts of each gene in the cellbender output, for cellbender-determined cells only (`np.array(adata_cellbender..X[cell_logic].sum(axis=0)).squeeze()`)
- `fraction_removed`: This is the fraction of counts of each gene that have been removed by cellbender (`(adata.var['n_raw'] - adata.var['n_cellbender']) / adata.var['n_raw']`)

If you just want to know what are the cells kept/removed by cellbender, you just need to look at `'latent_cell_probability'`.  It's in different places depending on if you load the whole dataset, or just the barcodes analyzed by cellbender.  If you load the barcodes analyzed by cellbender, then `'latent_cell_probability'` will be the same size as the number of droplets in the matrix (the analyzed droplets), and so `'latent_cell_probability'` goes in `adata.obs`.  If you load _all_ the droplets in the dataset, then `'latent_cell_probability'` will not be the same size as the number of droplets in the dataset, so it must be stored in `adata.uns`.  There are many ways to get what you want.

The simplest way so that you don't have to do anything yourself would be to just look at the `_cell_barcodes.csv` output file from cellbender.  This lists all the barcodes determined to have been cells.

If you want to know what droplets are _not_ cells, it's all the other ones.

Does that make sense?

If you want to use the `anndata_from_h5()` function and do this in `scanpy`, then try this (sorry about errors previously, I had not tested my responses before putting them up here):
```python
import scanpy as sc
import numpy as np

# load data
adata_raw = sc.read_10x_h5('INPUT_FILE.h5')
adata = anndata_from_h5('CELLBENDER_OUTPUT_FILE.h5', analyzed_barcodes_only=True)  # only load the analyzed barcodes

adata_cells = adata[adata.obs['latent_cell_probability'] > 0.5].copy()
```

which barcodes are called cells (non-empty) by cellbender?
```python
adata_cells.obs_names
```
which barcodes are called empty by cellbender?
```python
[bc not in adata_cells.obs_names for bc in adata_raw.obs_names]
```
