### ISSUE TITLE
Running CellBender without graphic card

### ISSUE THREAD

**Issue by nadinegheziel** [broadinstitute/CellBender#161]
Hello, 
Thank you very much for your hard work. 
I am trying to run CellBender on my data, but I have an issue : 

"    assert torch.cuda.is_available(), "Trying to use CUDA, " \
AssertionError: Trying to use CUDA, but CUDA is not available."

I finally understood that I didn't have a graphic card on my work computer. Is it any way to run CellBender without graphic card ? 
I am very not familiar with all of this, i am sorry if it doesn't make sense. 

Respectfully, 
Nadine

**Comment by sjfleming** [comment]
Hi Nadine,

Glad you're trying out CellBender!

There are two answers to your question:

1. The simple answer is "yes": you can run CellBender without a GPU.  You need to remove the flag `--cuda` from your cellbender command.  So instead of 

```
cellbender remove-background --cuda --input INPUT_FILE.h5 --output OUTPUT_FILE.h5 ...
```
(where the `...` is the rest of the command: whatever other inputs you want to use)
you would use the following command:
```
cellbender remove-background --input INPUT_FILE.h5 --output OUTPUT_FILE.h5 ...
```
(just omit `--cuda`)

2. The slightly more complicated answer is that, while CellBender _can_ run on CPU without a GPU, it is quite slow that way.  CellBender is really meant to be run on a GPU.  There are two options I know of for running CellBender on a GPU when you don't actually own a machine with a GPU:
        - You can run CellBender on Terra (https://app.terra.bio), which runs workflows in Google Cloud.  You use Google's GPU hardware instead of your own.  Of course, somebody has to pay for it... Google gives you several hundred dollars in free credits to start out with, so that could work for a while, but eventually your lab or company or somebody would need to pay for compute.
        - You can try to run CellBender using a Jupyter notebook on Google Colab (https://colab.research.google.com/; https://research.google.com/colaboratory/faq.html; https://neptune.ai/blog/google-colab-dealing-with-files), which allows you to use a GPU for totally free: the catch is that you can get kicked off the machine at any time, and if your CellBender run has not completed, you'd have to start over and try again.  Some users have told me that this has worked for them.  If you're not super familiar with Jupyter, then I should point out that you can run the cellbender command from a notebook cell by putting an exclamation point in front of it (https://stackoverflow.com/questions/38694081/executing-terminal-commands-in-jupyter-notebook), so something like `! cellbender remove-background --cuda ...` (And you'll also have to install CellBender)

Please let me know if you have any other questions as you try it out.

**Comment by nadinegheziel** [comment]
I can't thank you enough for your help, it all worked well and I could run CellBender on my data 
I will keep in touch once I will analyze the output

Thank you again,
Kindly 
Nadine
