### ISSUE TITLE
cellbender seems to idle after epoch calculation

### ISSUE THREAD

**Issue by Dimmiso** [broadinstitute/CellBender#168]
Hi, 
Thanks a lot for supporting CellBender! I have high expectations to it but my attempts to make it to work failed so far. 
As a test I run cellbender with 5-25 epochs (under one hour batch job). Epochs are calculated well (as I reason from a log file, attached) but then not much happens for next 10-50 minutes (depending on number of run epoches) until my cluster batch session closes because time runs out. The only output file produced by cellbender is a log file (attached; fused together with conda log file). I assumes that writing other output files should not take so long time for cellbender? 

my cellbender command was: 

cellbender remove-background \
                 --input /crex/proj/snic2017-7-434/private/UD/10xMonkey/DATA/P21828_1003_UD3/outs/raw_feature_bc_matrix.h5 \
                 --output CellBender_output/output_UD03_btchhh2c2.h5 \
                 --expected-cells 1000 \
                 --total-droplets-included 12000 \
                 --fpr 0.01 \
                 --epochs 25

How I can make cellbender to finish the task? 

Thanks a lot!
[UD03_output_btch2c2.txt](https://github.com/broadinstitute/CellBender/files/10033083/UD03_output_btch2c2.txt)

Dmitry

**Comment by sjfleming** [comment]
Hi Dmitry,

Yes, so I think I know what's happening.  There is a step happening after the "training" part (where you see all the epochs) which is computing the posterior.  (The log file needs to make this a bit more clear...)  So that point where you get cut off is actually a very expensive computational step which is computing the posterior of the model (the actual noise counts).

The reason it's taking so long and seeming to hang forever is that it really does take a long time on a CPU, without a GPU.  (Version 0.3.0 will be a bit faster). But CellBender is really meant to be run on a GPU if at all possible.

Any chance you could try it on a GPU with the `--cuda` argument?  (I'm guessing probably not, and that's why you're running into this issue.)  You might be able to try using a free GPU on google colab, some users have had success with that.

**Comment by Dimmiso** [comment]
Hi Stephen, 
Thanks a lot for quick and detailed answer! Unfortunately there are only cpus on a cluster I used, to my knowledge. But for this job I used 1 h of full node (20 cpus, 128 gb ram). I used that short time limit because this gives a queue priority for cluster calculation. If you think the script behaves as it should I can easily increase calculation session time or/number of used nodes (not sure what is more reasonable, if anything). Could I go around by increasing numbers or nodes (cpus) I use? 
Cannot it be also the case that since I used too few epochs (5-25) this not optimal intermediate results slows down subsequent calculations? (sorry, have very little idea how your algorithm works)
Thanks a lot again!
Dmitry

**Comment by sjfleming** [comment]
Hi Dmitry,

Yes, in short, I think the tool is probably behaving as expected, and if I were you I'd try it out with a larger time limit.  (Like really long... some people have told me it can take like 24 hours on CPU depending on the size of the dataset, but hopefully it doesn't take that long for you.)

Unfortunately, increasing the number of CPUs will not help much (if at all).

And I think the subsequent calculation of the posterior should actually take (almost) the same amount of time whether or not the algorithm has actually trained for a full number of epochs.

**Comment by Dimmiso** [comment]
Hi, 
thanks a lot! I will see if I can get access to GPU(s). It is also a bit pity that log does not make any records on the posteriors calculation progress (similar to epoch calculation), which would allow estimation of required time.
Thanks a lot!
Dmitry

**Comment by sjfleming** [comment]
It's a good point, I could include that in the future...

**Comment by sjfleming** [comment]
I have included these kinds of log file outputs in v0.3.0, and I think it was a good idea!

Closed by #238
