### ISSUE TITLE
All droplets called as cells with a probability of 1

### ISSUE THREAD

**Issue by djlmt** [broadinstitute/CellBender#170]
Hi there - I have been running the CellBender on my sc data. However, the result showed that all droplets were called as cells with a probability of 1. I tried fdr from 0.01 to 0.3, yet the problem remians Any thoughts? Thanks.

**Comment by djlmt** [comment]
Here are my command line and the result.

`cellbender remove-background --input ~outs/raw_feature_bc_matrix.h5 --output output.h5 --expected-cells 12203 --total-droplets-included 30000 --fpr 0.3 --epochs 150`

<img width="762" alt="Screen Shot 2022-11-30 at 11 07 05" src="https://user-images.githubusercontent.com/42179554/204848803-70a30a04-16dc-408f-928d-44cf7c07f50f.png">

**Comment by sjfleming** [comment]
Yeah CellBender is definitely making a mistake here.  However, I would consider this dataset to be in the "extremely challenging" category.  Based on that UMI curve, what would you, as the person who knows about the experiment, expect to see?

To me, it looks challenging because I don't see any clear distinction between what I'd expect to be cells and what I'd call "empty".  The dataset has a lot of counts overall.  If those are all empty droplets from droplet 10,000 onward, then they have about 2000 UMI counts each, which is quite a lot.  Do you expect such high ambient counts in this experiment?  Cells also have extremely high counts.

To me it looks like there might be a very very small bump at maybe like droplet 100 or 200, around 10^5 UMI counts.  I don't think I see a bump of any kind near droplet 12000, which you chose for the "expected cell count".  Based on my guesses,  you could try something like

```
cellbender remove-background \
    --input ~/outs/raw_feature_bc_matrix.h5 \
    --output output.h5 \
    --expected-cells 200 \
    --total-droplets-included 10000 \
    --fpr 0.01 \
    --epochs 150
```
(also I recommend using `--cuda` if you have access to a GPU.)

and just compare and see what happens.

**Comment by djlmt** [comment]
Thanks, @sjfleming. And yes, due to the nature of the experiment, we do expect to see high level of ambient counts. I will give a try and see. I will get back to you once I has the analysis done. Thanks so much again.

**Comment by djlmt** [comment]
Thanks, @sjfleming. And yes, due to the nature of the experiment, we do expect to see high level of ambient counts. I will give a try and see. I will get back to you once I has the analysis done. Thanks so much again.

**Comment by djlmt** [comment]
Thanks @sjfleming. Running with a small number for the expected cells fix the plot issue, yet this particular dataset seems challenging for the CellBender as you suggested. Thanks a lot though.
