### ISSUE TITLE
How does cellbender call cells? What is the difference to cellranger?

### ISSUE THREAD

**Issue by cheng-xiaoxiaoo** [broadinstitute/CellBender#176]
When I use cellranger or cellbender to filter cell from raw RNA count matrix, the results they output are allways different. Each of them can call some cells not appearing in other's result. So, how does cellbender call cells? Is it different to cellranger?

**Comment by sjfleming** [comment]
Yes @cheng-xiaoxiaoo , cellbender does something very different than cellranger when it comes to identifying cells.  Firstly, I should say that cellbender really distinguishes "empty" from "non-empty" droplets.  So everything called a "cell" by cellbender is really "non-empty".  The distinction is that those "non-empty" droplets are not all necessarily good cells.  You still need to do cell QC after cellbender to filter out droplets that have debris instead of a cell, or dying cells, etc.

Typically I see cellbender call more cells than cellranger, and almost always, the vast majority (if not all) cells called by cellranger are included in the calls made by cellbender.

CellBender calls cells based on doing inference in a probabilistic latent variable model of the data.  There is a latent variable which describes the probability that each droplet is non-empty.  After doing inference, we obtain a probability per cell that tells us how likely it is that the droplet was non-empty.  Many things go into the inference of this value, including counts per droplet as well as the gene expression profile itself.

For more details, I refer you to sections 2.1 and 3.2 of the manuscript here
https://www.biorxiv.org/content/10.1101/791699v2.full
