### ISSUE TITLE
Where in output is contamination fraction per droplet?

### ISSUE THREAD

**Issue by reliscu** [broadinstitute/CellBender#181]
Apologies if I'm missing something obvious, but looking at the outputs from CellBender, **I do not see estimated contamination fraction for each droplet**, which, according the the [CellBender vignette](https://cellbender.readthedocs.io/en/latest/getting_started/remove_background/index.html#run-remove-background), should be part of the output.

Listing the h5 file contents:
```
h5ls(files[grep("output.h5", files)])
              group                           name       otype  dclass         dim
0                 /                         matrix   H5I_GROUP                    
1           /matrix             ambient_expression H5I_DATASET   FLOAT       36601
2           /matrix    barcode_indices_for_latents H5I_DATASET INTEGER       20000
3           /matrix                       barcodes H5I_DATASET  STRING      218838
4           /matrix  contamination_fraction_params H5I_DATASET   FLOAT           2
5           /matrix                           data H5I_DATASET INTEGER     3165911
6           /matrix                       features   H5I_GROUP                    
7  /matrix/features                   feature_type H5I_DATASET  STRING       36601
8  /matrix/features                         genome H5I_DATASET  STRING       36601
9  /matrix/features                             id H5I_DATASET  STRING       36601
10 /matrix/features                           name H5I_DATASET  STRING       36601
11          /matrix fraction_data_used_for_testing H5I_DATASET   FLOAT       ( 0 )
12          /matrix                        indices H5I_DATASET INTEGER     3165911
13          /matrix                         indptr H5I_DATASET INTEGER      218839
14          /matrix              lambda_multiplier H5I_DATASET   FLOAT       ( 0 )
15          /matrix           latent_RT_efficiency H5I_DATASET   FLOAT       20000
16          /matrix        latent_cell_probability H5I_DATASET   FLOAT       20000
17          /matrix           latent_gene_encoding H5I_DATASET   FLOAT 100 x 20000
18          /matrix                   latent_scale H5I_DATASET   FLOAT       20000
19          /matrix  overdispersion_mean_and_scale H5I_DATASET   FLOAT           2
20          /matrix                          shape H5I_DATASET INTEGER           2
21          /matrix     target_false_positive_rate H5I_DATASET   FLOAT       ( 0 )
22          /matrix                      test_elbo H5I_DATASET   FLOAT          30
23          /matrix                     test_epoch H5I_DATASET INTEGER          30
24          /matrix        training_elbo_per_epoch H5I_DATASET   FLOAT         150
```

**Comment by sjfleming** [comment]
Hi @reliscu , that's a good point... I don't currently compute that value and store it in the output.  I had forgotten that I wrote that in the docs.

You can compute the contamination fraction per droplet simply by subtracting the cellbender output count matrix from the input count matrix, and summing over genes (and then making it a fraction of input counts).
You can do it as follows using an AnnData object in python:
```python
from cellbender.remove_background.downstream import load_anndata_from_input_and_output

adata = load_anndata_from_input_and_output(
    input_file=raw_input_h5_file, 
    output_file=cellbender_output_h5_file,
    input_layer_key='raw',
)
```
That function precomputes a few things, including `adata.obs['n_raw']` and `adata.obs['n_cellbender']`, and then the contamination fraction per droplet can be computed as
```python
adata.obs['contamination_fraction'] = (
    (adata.obs['n_raw'] - adata.obs['n_cellbender']) 
    / adata.obs['n_raw']
)
```

The function `load_anndata_from_input_and_output` is here: 
https://github.com/broadinstitute/CellBender/blob/1f49c82f123d10f83574e8e5ffa10094f8dc211a/cellbender/remove_background/downstream.py#L179
You can import it as above only if you have a local installation from github that would allow you to use the `sf_dev_0.3.0_postreg` branch, which is where that `downstream.py` file currently lives.  Otherwise you can copy and paste the contents of that `downstream.py` file somewhere convenient for you.

**Comment by reliscu** [comment]
Hi @sjfleming,

Thanks for the quick response!

Makes sense -- will give that a try.

Best,
Rebefcca
