### ISSUE TITLE
Remove background in ADT assay

### ISSUE THREAD

**Issue by kvshams** [broadinstitute/CellBender#182]
Hi @sjfleming,
Is there any additional parameters required for running remove background for both RNA and ADT assays or the default parameters are enough for the first pass?.
Thanks,
Shams

**Comment by sjfleming** [comment]
Hi Shams!  By data with both RNA and ADT assays, are you referring to CITE-seq data?

If so, then remove-background should work without doing anything special.  The default parameters should work.  (But let me know if you run into a problem...)

**Comment by kvshams** [comment]
Thanks @sjfleming! I closing this issue for now and reopen if I running to other problems.

**Comment by sjfleming** [comment]
Okay actually... one thing I will say is that if the antibody-tagged features are very very noisy (which they usually are), then sometimes you can benefit from cranking up the `--fpr` more than usual.  For example, I usually use `0.01` all the time for RNA data, but I've noticed that it's often useful to use a value of `0.05` or `0.1` for CITE-seq data.

(In the future, I might consider adding some functionality to enable people to set different FPR target values for different modalities...)

**Comment by sjfleming** [comment]
Hi @npklein , the idea was that you should be able to use the flag `--exclude-antibody-capture` when running cellbender; however, I've been told that some user are seeing errors when trying that flag.  It seems there is a bug currently, which I will be fixing soon.

In the meantime, I would recommend one of two options:
1. run with both GEX and the antibody features.  (CellBender does a great job on the antibody features, see https://www.biorxiv.org/content/biorxiv/early/2022/07/12/791699/F5.large.jpg?width=800&height=600&carousel=1 from the preprint here https://www.biorxiv.org/content/10.1101/791699v2.full).  If you want to use the raw counts for the antibody features, you can replace the cellbender outputs with the raw counts after the run.
2. manually remove the antibody features from the h5 file before running cellbender.  But this is more work, and there's really no reason to do this (that I can think of) instead of option (1).

**Comment by yuhsinhsieh-josch** [comment]
Hi Stephen,

I would like to use the CellBender for ADT (> 100 Abs), but it's not with standard 10X feature barcode method, so the ADT matrix is not in the same h5 file as GEX. Also in same cases we have ATAC and ADT instead of GEX.

For the dataset with GEX and CITE-seq, wold you recommend to combine both GEX and ADT feature together, and then run CellBender? And also wonder if CellBender work with ADT assay alone (given I read other issue that CellBend seems to be not compatible with ATAC data)?

Thanks!
Josch

**Comment by sjfleming** [comment]
Hi Josh @yuhsinhsieh-josch , good questions.

I would recommend trying to combine the ADT and GEX data before running cellbender.  The easiest way to do this might be to use scanpy/anndata to load both datasets separately, and then join them together into one:
https://anndata.readthedocs.io/en/latest/generated/anndata.concat.html

Then you can write the anndata object to an h5ad file, and cellbender can read the h5ad file as input.  Just make sure you include all the empty droplets as well!

(I'm assuming the droplet barcodes for the GEX data and the ADT data are the same set of barcodes right?  Like, you're measuring GEX and ADT in the very same cells?)

CellBender will probably not work very well with ADT alone, although you have an interesting test case!  [I did write that you cannot use ADT alone in the documentation](https://cellbender.readthedocs.io/en/latest/troubleshooting/index.html#a24)... but I was assuming people would only have like 10 antibody tags.  With 100 antibodies, you might actually be getting into the regime where cellbender could run using ADT alone.

The idea is that cellbender needs to be able to create a decent prior on "cell type" based on the input features.  With 10 antibodies, this is not enough to make a good UMAP of cell type.  But with 100 antibodies, you might just check and see: if you use those 100 ADT features alone and try to make a UMAP in the standard way (without cellbender), do you get cells clustering by cell type?  If so, you probably can try to run cellbender using only your > 100 ADT features.

As far as ATAC goes, here's a few thoughts:

- I have tried running ATAC features through cellbender.  It will work, but it might take a long time.  Consider setting the input parameter `--projected-ambient-count-threshold 2` to limit the number of features cellbender will analyze and save a whole lot of time.
- Some people opt to exclude ATAC features from cellbender analysis, and you can do this via `--exclude-feature-types Peaks` (assuming 10x data)
- Anecdotally I've been told that there is not a whole lot of noise in ATAC data.  But I'm open to hearing differing opinions.

Something experimental you could try:

This is a strange idea... but assuming your 100 ADT features are not quite enough on their own, and you still want to denoise those ADT features in the case where you have only ATAC + ADT but no GEX, then you might try the following...

Make a new h5ad file which has all the ADT features and only [the top 2000 highly-variable ATAC features](https://scanpy.readthedocs.io/en/stable/generated/scanpy.pp.highly_variable_genes.html#scanpy.pp.highly_variable_genes) (I recommend `flavor='seurat_v3'`).  Then include all those ~ 2100 features in the cellbender analysis.  And then use the output denoised counts of the ADT data, but just use the raw data for all the ATAC features.  This will allow cellbender to construct a nice strong prior on cell type using the highly variable ATAC features, but it will not take forever to run.

**Comment by sjfleming** [comment]
Also for ADT data it's sometimes interesting to try to run with different `--fpr` values (since ADT features often have so much background noise).  The default of `--fpr 0.01` is probably going to do a fine job, but if you find you'd like even less noise (at the expense of removing a bit of signal), then you can try `--fpr 0.1` for comparison.
