### ISSUE TITLE
Understanding cellbender plots

### ISSUE THREAD

**Issue by smk5g5** [broadinstitute/CellBender#211]
[sample_001.pdf](https://github.com/broadinstitute/CellBender/files/11408989/sample_001.pdf)
[sample_014.pdf](https://github.com/broadinstitute/CellBender/files/11408993/sample_014.pdf)

Hi ,

I am trying to understand the cellbender output. Attached are the plots of 2 of the samples (from a multiple of samples) that I am analysing. As you can see these two plots are uncharacteristically different from each other. As far as my data is concerncer these two plots are at the opposite ends of the spectrum and other plots are in between. All the runs were done using your WDL pipeline with default parameters.

I am trying to understand what these plots mean and from what I have read from your paper the ELBO plot  just shows how well the training and testing data converge with each other which looks OK for both I think.

I am not sure how to interpret the next two plots i.e. UMI counts vs barcode index plot and the PCA of latent encoding of cell gene expression. 

I am particularly concerned about sample 14 in this case. Do you think it looks appropriate to you? If so why?

It would help greatly if there are multiple examples somewhere showing what plots are acceptable plots and which aren't.

Thank you!

**Comment by sjfleming** [comment]
Hi @smk5g5 , thanks for writing in, and glad you were able to use the WDL.

I see the two plots.  You're correct: the ELBO plots look great for both samples.

The second plot (which barcodes contain cells) for sample 001 looks very typical, and it looks appropriate to me.

The second plot for sample 014 looks suboptimal.  The reason (I believe) is that there have not been enough droplets included in the analysis:
<img width="763" alt="image" src="https://user-images.githubusercontent.com/10214815/236869142-95688efc-0f3b-43fc-accd-4ee445477292.png">

the 30k droplets used (I'm guessing `--total-droplets-included` was 30k?) seems to be too few.  The algorithm has determined that almost all 30k droplets are "non-empty" (the red line, cell probability near 1).

If you include more droplets (not sure exactly how many since I cannot see the whole UMI curve, but maybe 40k?), then the algorithm will be able to more clearly differentiate between cell-containing and empty droplets.

Right now, the output is probably not super problematic for sample 014, but you are likely missing out on some cells from your dataset that lie beyond droplet 30k in the UMI curve, so I would suggest re-running with `--total-droplets-included 40000` or whatever number you think is right (following [this advice](https://cellbender.readthedocs.io/en/latest/usage/index.html#recommended-best-practices)).

One rule of thumb: I like to see the red line for cell probability start at 1 on the left hand side, and end at 0 on the right hand side, like sample 001.  That gives me confidence that "all the cell-containing droplets have been found":
<img width="758" alt="image" src="https://user-images.githubusercontent.com/10214815/236871434-c24504dd-2074-4ea4-8ef8-2cf33a9317ab.png">


The third plot is extremely qualitative, but it can still be interesting to look at.  For sample 001, I'd say it looks great, and I'd suspect you might have 3 (or 4, 5, or 6 or so) major cell types in your dataset.  For sample 014, there are not many conclusions I can draw from this plot, but it might start to look a bit more like the plot for sample 001 if more droplets are included and more cells are identified.  But if it stays looking like it does now, there's no problem with that either.  It just indicates that cellbender found that "cell types" were less discrete in this dataset, or maybe there was only one or two major cell types in the experiment.

**Comment by smk5g5** [comment]
I thought the output looked noisier for sample01 as well. Anyway if you would not mind could you tell which of these datasets need to be rerun with changed parameters. From the discussions in githu
[sample_002_out.pdf](https://github.com/broadinstitute/CellBender/files/11422808/sample_002_out.pdf)
[sample_003_out.pdf](https://github.com/broadinstitute/CellBender/files/11422809/sample_003_out.pdf)
[sample_004_1_out.pdf](https://github.com/broadinstitute/CellBender/files/11422810/sample_004_1_out.pdf)
[sample_004_2_out.pdf](https://github.com/broadinstitute/CellBender/files/11422811/sample_004_2_out.pdf)
[sample_005_1_out.pdf](https://github.com/broadinstitute/CellBender/files/11422812/sample_005_1_out.pdf)
[sample_005_2_out.pdf](https://github.com/broadinstitute/CellBender/files/11422813/sample_005_2_out.pdf)
[sample_007_1_out.pdf](https://github.com/broadinstitute/CellBender/files/11422814/sample_007_1_out.pdf)
[sample_007_2_out.pdf](https://github.com/broadinstitute/CellBender/files/11422815/sample_007_2_out.pdf)
[sample_008_1_out.pdf](https://github.com/broadinstitute/CellBender/files/11422816/sample_008_1_out.pdf)
[sample_008_2_out.pdf](https://github.com/broadinstitute/CellBender/files/11422817/sample_008_2_out.pdf)
[sample_010_1_out.pdf](https://github.com/broadinstitute/CellBender/files/11422818/sample_010_1_out.pdf)
[sample_010_2_out.pdf](https://github.com/broadinstitute/CellBender/files/11422819/sample_010_2_out.pdf)
[sample_013_1_out.pdf](https://github.com/broadinstitute/CellBender/files/11422821/sample_013_1_out.pdf)
[sample_013_2_out.pdf](https://github.com/broadinstitute/CellBender/files/11422822/sample_013_2_out.pdf)
[sample_014_1_out.pdf](https://github.com/broadinstitute/CellBender/files/11422823/sample_014_1_out.pdf)
[sample_014_2_out.pdf](https://github.com/broadinstitute/CellBender/files/11422824/sample_014_2_out.pdf)
b issues it looks like zdim,z-layers etc might also need to be changed. Here are the results after running with lower fpr and lower learning rate (i.e. 10-5)

Do you think any of these need to be rerun with different parameters for better fit?

Thank you!

**Comment by sjfleming** [comment]
You've got some cool looking samples here   :)

- 002: great
- 003: great
- 004_1: great
- 004_2: you may be missing cells here.  the UMI curve only goes out to 30k and the UMI counts per droplet are still around 300.  they're not going to be great quality cells, but there still might be some "non-empty droplets" out beyond 30k.  it helps cellbender to include all the droplets until you're really sure the rest are "surely empty".  I'd try `--total-droplets-included 40000`
- 005_1: great
- 005_2: great
- 007_1: magnificent
- 007_2: very interesting looking cell probability plot and I like it.  great.  (the ambient RNA level looks very very low in this dataset to begin with)
- 008_1: great
- 008_2: fine
- 010_1: great
- 010_2: great
- 013_1: great
- 013_2: fine
- 014_1: excellent
- 014_2: same problem as 004_2 with the same suggested fix: more `--total-droplets-included`.  here the UMI counts are still over 1000 at droplet 30k, which probably means you've still got good cells out there and beyond.

**Comment by smk5g5** [comment]
So you think MEN002 looks ok? The cell probability plot looks all over the place (but may be I still don't understand how to interpret the probability plot here)

**Comment by sjfleming** [comment]
Yeah I think that's okay.  The cell probability plot does include a handful of rather low-count (150-300 UMIs) droplets as having > 0.5 posterior probability of being "non-empty"... but I think that's just part of the idiosyncrasies of this dataset.  I see that kind of thing pretty often, and it doesn't indicate any problem.

I would recommend always doing cell QC after cellbender, and I'd imagine that even though cellbender thinks some of those droplets < 300 UMI counts are "non-empty", they might not really contain great quality cells that you want to include downstream.

I think of the cell calls as being great for "eliminating actual empty droplets" but I still do cell QC to eliminate poor quality droplets after cellbender.

**Comment by smk5g5** [comment]
By cell QC are you implying there is a tool by that name or general quality control (i.e. remove dead cells based on mitochondrial gene expression etc)?

**Comment by sjfleming** [comment]
The latter: general quality control.  Unfortunately I have not found a great one-size-fits-all tool for this.

**Comment by smk5g5** [comment]
Is there a way to know how much ambient RNA was removed from each sample from cellbender output?

**Comment by smk5g5** [comment]
![image](https://github.com/broadinstitute/CellBender/assets/6811915/852f06ac-4dc0-417a-882d-bc3686ff7d87)

A lot of these cells are supposed to be tumor cells but we see CD14 expression here when we are not supposed to.
What do you think are the possible reasons for seeing CD14 expression even after ambient RNA removal?  Our theory is that this could be due to the bursting of macrophages which has caused it. In that scenario shouldn't Cellbender be able to remove that signal?

**Comment by sjfleming** [comment]
> Is there a way to know how much ambient RNA was removed from each sample from cellbender output?

Yes.  You can do something as simple as subtracting the cellbender count matrix from the raw count matrix.  If you use `anndata` and use the loading functions [here](https://github.com/broadinstitute/CellBender/blob/sf_dev_0.3.0_postreg/cellbender/remove_background/downstream.py), you could implement this with something like

```python
from cellbender.remove_background.downstream import load_anndata_from_input_and_output
import numpy as np

adata = load_anndata_from_input_and_output(input_file='RAW.h5', output_file='CELLBENDER.h5', input_layer_key='raw')
removed_count_matrix = adata.layers['raw'] - adata.layers['cellbender']
adata.obs['counts_removed'] = np.array(removed_count_matrix.sum(axis=1)).squeeze()
adata.obs[['sample', 'counts_removed']].groupby('sample').sum()
```

--------------

> we see CD14 expression

There are definitely reasons you might still see off target expression even after cellbender:
1. The expression is not really off target, even though you expect it to be
2. The expression is off target, but it was not removed by cellbender (you could try a larger `--fpr` value)

The only scenario where cellbender will not remove noise is a scenario where the noise is structured in a way that is inconsistent with cellbender's mathematical model of noise: i.e. noise should be Poisson sampled from an ambient noise profile that is equal to the empty droplet expression profile (plus noise due to barcode swapping, which is noise proportional to total UMI counts in each droplet).  If you had transcriptional bursting of CD14 in macrophages, so that some macrophages express high levels and other macrophages express lower levels, cellbender will see that as real signal, and will not remove it.  If there is CD14 everywhere, including in empty droplets, cellbender will try to remove that appropriate amount of CD14 from everything.

One question about the above plot of CD14 though: the plots really look identical.  Are you sure they are different?

**Comment by smk5g5** [comment]
I used the tool here for this. https://samuel-marsh.github.io/scCustomize/articles/Cell_Bender_Functions.html
And it looks like there is no difference in nCount for CD14 between cellbender and cellranger output.
```
Raw_Counts CellBender_Counts Count_Diff Pct_Diff
CD14       3057              3057          0        0
```

**Comment by sjfleming** [comment]
Oh wow, that function and its documentation look awesome, Samuel Marsh did a great job on that.

Alright yeah, hmmm, how about some other genes?  Is CellBender removing anything at all from the count matrix?  

If you look in the empty droplets, do you see CD14?

**Comment by sjfleming** [comment]
Will close for now, feel free to re-open
