### ISSUE TITLE
index 14365 is out of bounds for axis 0 with size 14365

### ISSUE THREAD

**Issue by nouhaylaeraysy** [broadinstitute/CellBender#225]
Hello , 
i'm using cellBender i run this command : 
cellbender remove-background --input /home/yanis/Bureau/Data2/filtered_feature_bc_matrix_larva1_virilis --output output.h5 --expected-cells 25000 --total-droplets-included 50000 --low-count-threshold 50 --fpr 0.01 --learning-rate 1.0E-7

But it gives me an error like this: 
return torch._C._cuda_getDeviceCount() > 0
cellbender:remove-background: Command:
cellbender remove-background --input /home/yanis/Bureau/Data2/filtered_feature_bc_matrix_larva1_virilis --output output.h5
cellbender:remove-background: 2023-06-21 16:22:53
cellbender:remove-background: Running remove-background
cellbender:remove-background: Loading data from directory /home/yanis/Bureau/Data2/filtered_feature_bc_matrix_larva1_virilis
cellbender:remove-background: CellRanger v3 format
cellbender:remove-background: Trimming dataset for inference.
cellbender:remove-background: Including 14239 genes that have nonzero counts.
cellbender:remove-background: Prior on counts in empty droplets is 896
cellbender:remove-background: Prior on counts for cells is 8876
cellbender:remove-background: Excluding barcodes with counts below 448
Traceback (most recent call last):
  File "/home/yanis/miniconda3/envs/cellbender/bin/cellbender", line 8, in <module>
    sys.exit(main())
  File "/home/yanis/miniconda3/envs/cellbender/lib/python3.7/site-packages/cellbender/base_cli.py", line 101, in main
    cli_dict[args.tool].run(args)
  File "/home/yanis/miniconda3/envs/cellbender/lib/python3.7/site-packages/cellbender/remove_background/cli.py", line 109, in run
    main(args)
  File "/home/yanis/miniconda3/envs/cellbender/lib/python3.7/site-packages/cellbender/remove_background/cli.py", line 204, in main
    run_remove_background(args)
  File "/home/yanis/miniconda3/envs/cellbender/lib/python3.7/site-packages/cellbender/remove_background/cli.py", line 159, in run_remove_background
    fpr=args.fpr)
  File "/home/yanis/miniconda3/envs/cellbender/lib/python3.7/site-packages/cellbender/remove_background/data/dataset.py", line 101, in __init__
    gene_blacklist=gene_blacklist)
  File "/home/yanis/miniconda3/envs/cellbender/lib/python3.7/site-packages/cellbender/remove_background/data/dataset.py", line 339, in _trim_dataset_for_analysis
    [last_analyzed_bc])
IndexError: index 14365 is out of bounds for axis 0 with size 14365

Do you have an idea how i can solve this? 
Thank you in advance.
Best

**Comment by PaulRivaud** [comment]
Ran into the exact same issue. Any help would be appreciated.
Thank you

**Comment by nouhaylaeraysy** [comment]
Hello , 
Thank you for your response yes i try to run cellranger with the raw data but the comand take more than 6 hours and still at this step : "Optimal posterior regularization factor" Do you know how i can solve this ?
Thank you again
Best

**Comment by sjfleming** [comment]
Yes, unfortunately it will take a very long time to run on a CPU.  We definitely recommend running the tool on a GPU with the `--cuda` flag, if possible.  Otherwise you may have to wait a while.  The other thing you can try is running the code from the branch `sf_dev_0.3.0_postreg` in this repository.  It's a newer version (which will eventually be released as v0.3.0, or something very close to it), and it may be faster.

**Comment by nouhaylaeraysy** [comment]
I didn't manage to install cuda on my machine , i tried to pull the Docker image but when i run my command : 
'cellbender remove-background  --input /home/yanis/Téléchargements/raw_feature_bc_matrix.h5  --output output.h5  --expected-cells 15000  --total-droplets-included 20000  --fpr 0.01 --epochs 150 --cuda "


i have this error : 
assert torch.cuda.is_available(), "Trying to use CUDA, " \
AssertionError: Trying to use CUDA, but CUDA is not available.

**Comment by sjfleming** [comment]
Yes, if you have GPU hardware, then you need to try to debug why your pytorch installation is not recognizing it.  (If you do not have a GPU machine, then cuda will not install successfully.  You may want to look into using [Terra](app.terra.bio) or [google colab](colab.google.com).)  But assuming you do have a GPU, then I would try to do this

```
pip install torch
```
and then in python run
```python
import torch
torch.cuda.is_available()
```
and see if it says `True`.

**Comment by nouhaylaeraysy** [comment]
Thank you for your help,
So on my machine i have just the CPU i don't have the GPU , where i can find the branche "sf_dev_0.3.0_postreg" in cellbender ? 

Best,
Nouhayla

**Comment by sjfleming** [comment]
Hi Nouhayla, sorry for the delay in responding.  Okay, if you have no GPU, then do not include the flag `--cuda` when you run the command.

The branch `sf_dev_0.3.0_postreg` lives in this GitHub repository, and it can be installed by doing the following (one of many ways to do it).  First, install Anaconda or miniconda and make sure the `conda` command is working.  Once it is, clone the cellbender repository:

```console
$ mkdir -p ~/Documents/Github
$ cd ~/Documents/Github
$ git pull https://github.com/broadinstitute/CellBender.git
```

This will create a folder `~/Documents/Github/CellBender` with the contents of this repository.  Then you need to install in editable mode and switch to the `sf_dev_0.3.0_postreg` branch.

```console
$ cd ~/Documents/Github/CellBender
$ conda create -n cellbender python=3.7
$ conda activate cellbender
(cellbender) $ git checkout sf_dev_0.3.0_postreg
(cellbender) $ pip install -e .
```

When you want to run cellbender, make sure you run `conda activate cellbender` first, so that you are working in the conda environment where cellbender is installed.

You can checkout and run any other branch as well by changing the line `git checkout sf_dev_0.3.0_postreg` to the branch of your choice.

**Comment by sjfleming** [comment]
These updates have just been merged, and have been released as part of v0.3.0, so you no longer have to go to that branch to get the updates, as long as you update cellbender to v0.3.0

Closed by #238

**Comment by nouhaylaeraysy** [comment]
Hello , 
It works Know , thank you verry much !
Best

**Comment by sjfleming** [comment]
Woohoo, great to hear!
