### ISSUE TITLE
There is an entry in the output greater than the input

### ISSUE THREAD

**Issue by jg9zk** [broadinstitute/CellBender#268]
In the cellbender html report, none of my samples passed the check that ensures no counts were added to the matrix. I used the default arguments for v0.3.0:

cellbender remove-background --cuda --input anndata_raw.h5ad --output anndata_cellbender.h5

![cellbender_error](https://github.com/broadinstitute/CellBender/assets/78545335/6de0aa88-d19a-447b-987f-93f95bb7f578)

**Comment by sjfleming** [comment]
Do you get the same error if you use this commit (same branch)?
```
8be31d2bc02f8ed12c314a10fba6e14c3eb8f901
```

If it's possible, I'd love to get a copy of that input `anndata_raw.h5ad` file for debugging purposes.  I've run several samples using the `7fd0ac` commit and I have not seen this error, so I think there's some kind of edge case happening.

**Comment by jg9zk** [comment]
Yes I am using 7fd0ac. If you're not seeing this problem, I'll see if my raw files are different than what you are expecting. The difference between counts seems to be limited to +1
![cellbender_count_diff](https://github.com/broadinstitute/CellBender/assets/78545335/6a7f054f-fa4b-4b4d-ba0b-fe8c65f7cb69)

**Comment by sjfleming** [comment]
Hm, okay here I am a little confused.  I think maybe I know what's going on...

Has the input .h5ad file had its count matrix normalized somehow?

The histogram you plotted seems to show that there are fractional count differences between input and output.  Everything in cellbender should be working with raw integer count values.

**Comment by sjfleming** [comment]
Very very interesting!  I did not realize that STARsolo's EM method would give non-integer count matrices.  That is really good to know, because I'm sure some people will run into this in the future as well.

To be honest, I'm a bit surprised that cellbender got all the way to the end without complaining... it computes probabilities using distributions like Poisson and negative binomial, where the observed counts should be integers... but I suppose the actual computation that happens can accommodate non-integers.  (Uses a lot of `.lgamma()` functions.)

It is very interesting to see that histogram though.  It seems like there are several million count matrix entries (presumably this is like 1% of all the nonzero count matrix entries?) that are increasing by a fractional count (potentially all < +1 count).  And the most popular value seems to be +0.5.  (Perhaps this has to do with a 0.5 fractional count being the most popular from the STARsolo EM algorithm?)

Because cellbender actually estimates the _noise_ counts (as an integer count matrix) and then constructs the final "denoised" count matrix by doing `input - estimated_integer_noise_counts`, I guess the cellbender output count matrix also contains fractional counts.  (Unless the process of writing to the h5 file forces a conversion to integers, but I don't think I'm doing that.)

**Comment by jg9zk** [comment]
- FYI CellRanger drops any UMI that maps to multiple loci, but almost all other mapping software have options to keep multimapped UMIs that yield non-integer count matrices. Bulk RNA-seq tools like edgeR have a way to handle this, but I don't think most single cell tools have this implemented. I think it's definitely worth a mention in the docs
- I don't think the probabilistic torch models throw an error or even a warning if you give them non-integer data, so you would need to write your own warning/error.
- Yeah I think mapping to 2 loci is the most common multimapping instance, and most algorithms just split the count between them (+0.5 count)

**Comment by sjfleming** [comment]
Actually, now I'm not crystal clear on one point.  The more I think about it, the more it seems like the only way cellbender would be adding even fractional counts is if there is some kind of round-off occurring.  Is the cellbender output count matrix an integer count matrix in your case?  The only scenario I can come up with in my head to explain _adding_ a fractional count would be:

1. cellbender estimates the integer noise count (for one particular count matrix entry) to be zero
2. the denoised count matrix is then `input - noise_counts` (for example, 0.5 - 0 = 0.5)
3. the denoised count matrix then gets rounded up (for example, 0.5 --> 1.  so the input was 0.5 but the output was 1)

Without (3), it would be hard for me to understand how even a fractional count is being added.

**Comment by jg9zk** [comment]
I already deleted those files, so I can't check what you're asking about. But, using raw counts instead of expected counts fixed the issue! Thanks for the help!
