### ISSUE TITLE
Feat: Using output from Kallisto/Bustools (or other non-CellRanger pipelines)

### ISSUE THREAD

**Issue by yfarjoun** [broadinstitute/CellBender#274]
CellRanger format is different than the native AnnData/scanpy format. and while AnnData knows how to import 10X files, it doesn't know how to export them....i.e. if I have data that wasn't generated by 10X I have a hard time running CellBender on it. It would be nice to have a way to input generic data by providing 
- where the data lives
- whether it's indexed by cells or genes
- what are the names of the various features that are needed for understanding the data.

The "normal" 10x run, would be invoking the generic pipeline with some set of inputs, but those of us who use non-CellRanger output could also have the benefit of using CellBender....

**Comment by sjfleming** [comment]
CellBender does now have the ability to take a variety of file formats as input.  It can take a CellRanger h5, but it can also take an AnnData h5ad file, or a dropseq DGE file (not recommended though because the input parsing takes forever on large samples), or a loom file (same note as DGE), or a CellRanger MTX formatted tuple of files.

The AnnData format and the MTX format are both general enough that I was hoping that most use cases would fall into one of those bins.  Is the AnnData option workable for you?  (Raw counts should be in `adata.X`... or for complete details see [here](https://github.com/broadinstitute/CellBender/issues/166#issuecomment-1317562488))

**Comment by yfarjoun** [comment]
ok. I'll give it a try.

**Comment by yfarjoun** [comment]
For the record, it seems to be working!! thanks!
