### ISSUE TITLE
Could not save checkpoint/cannot pickle 'weakref' object

### ISSUE THREAD

**Issue by ndrubins** [broadinstitute/CellBender#275]
Hi,

I'm getting this error running `remove-background`:

```
cellbender:remove-background: Saving a checkpoint...
cellbender:remove-background: Could not save checkpoint
cellbender:remove-background: Traceback (most recent call last):
  File "/home/miniconda/envs/py3_9/lib/python3.9/site-packages/cellbender/remove_background/checkpoint.py", line 115, in save_checkpoint
    torch.save(model_obj, filebase + '_model.torch')
  File "/home/miniconda/envs/py3_9/lib/python3.9/site-packages/torch/serialization.py", line 441, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "/home/miniconda/envs/py3_9/lib/python3.9/site-packages/torch/serialization.py", line 653, in _save
    pickler.dump(obj)
TypeError: cannot pickle 'weakref' object
```

It's reported in [this issue](https://github.com/broadinstitute/CellBender/issues/212), but the [Ilia Kats's pyro repo is gone](https://github.com/ilia-kats/pyro).

Any idea how to solve this?

Thanks

**Comment by sjfleming** [comment]
Hi @ndrubins , yes, this error happens when you use a version of pytorch >= 2.0

What is currently recommended is to install cellbender in an environment with python 3.7.  Python 3.7 was used to develop and test cellbender, and python 3.7 also limits the pytorch version to < 2.0.

I am working to make cellbender compatible with pytorch >= 2.0, but I have not quite figured it out.

The progress on that can be tracked here: #203

**Comment by plijnzaad** [comment]
Could you please put the strict requirement on python 3.7 and torch < 0.2.0 somewhere prominent in the installation instructions? Many people including myself are wasting a lot of time on trying to understand/solve this problem ...

**Comment by shihsama** [comment]
Hi @sjfleming ,
I’ve encountered the same issue. Since NVIDIA’s 50-series GPUs are based on the Blackwell, they are only compatible with CUDA 12.8 and above. However, CUDA 12.8 is only supported by PyTorch 2.8 and later versions, while the latest two versions of PyTorch require Python 3.10 or higher. This means that CellBender currently cannot use 50-series GPUs for acceleration.
