### ISSUE TITLE
QC Failure advice?

### ISSUE THREAD

**Issue by cnk113** [broadinstitute/CellBender#50]
I noticed on the docs that a QC failure looking plot would be problematic for empty droplet identification. I was wondering if you had any tips to get the most of these datasets? I have a decent number of QC failed looking datasets which I can't regenerate since the samples are very rare.

**Comment by sjfleming** [comment]
Yeah, I am guessing you are referring to "Exhibit C" in the docs here:
https://cellbender.readthedocs.io/en/latest/usage/index.html#remove-background

That is a difficult case.  I have seen my fair share of datasets that look like this, and when I have seen them, they have been nuclear scRNA-seq datasets that look like all of the nuclei have probably ruptured.  That would be a reasonable explanation for the fact that there's no discernible distinction between "cells" and "empty droplets" that you could make by eye.  Everything is an "empty droplet" filled with a similar (large) dose of ambient RNA.  If that is really the case, then unfortunately the dataset is really not useable.  I would discourage trying to glean anything from it -- but that is my opinion.

If you think there is some other possible explanation for that shape of UMI curve, then maybe there is a reason to try and salvage something.  But I struggle to think of a legitimate scenario that would cause that sort of a UMI curve.

If you really want to try something, I would set an upper limit on what you think the number of cells could possibly be, take those droplets, and create as many QC metrics as you can think of on a per-cell basis.  Use all these metrics to create filters in order to filter cells stringently.  Eliminate a lot.  Then try to normalize the data, find highly variable genes, cluster cells, and look for markers.  If you see legitimate-looking cell types, perhaps there is something to learn.  Maybe you can use the information in the lab to design further experiments.  But I would again discourage trying to draw any publication-worthy conclusions using a dataset that really doesn't pass QC.
