### ISSUE TITLE
High Background and CellBender retains too many nuclei 

### ISSUE THREAD

**Issue by aralbright** [broadinstitute/CellBender#77]
Hi, 

I have done single nucleus RNA-seq on two different time points with 10x v3. My later time point looks fine, but CellBender doesn't seem to be handling the earlier time point very well. I would expect the nuclei at this earlier time point to have much higher background signal because overall transcription is relatively low, but that leaves me with the issue of how to properly filter the data. 

Running CellBender without changing z-dim and z-layers as suggested in [this issue](https://github.com/broadinstitute/CellBender/issues/42) 

I get:

[cb_st3_output.pdf](https://github.com/broadinstitute/CellBender/files/5373186/cb_st3_output.pdf)

But when I change the z-dim to 20 and z-layers to 500 as suggested I get: 

[cb_st3_output_201012.pdf](https://github.com/broadinstitute/CellBender/files/5373191/cb_st3_output_201012.pdf)

Either way, while the expected number of nuclei is 10,000 and total droplets included is 15,000, CellBender retains over 14,800 nuclei. 

![Volcano Plots](https://user-images.githubusercontent.com/29262152/95897983-39493100-0d43-11eb-90a7-127bb0fa052d.png)

The mitochondrial % for many of these is extremely high, which is isn't totally unexpected but also is why I was hoping I'd be able to use remove-background. Now I'm not entirely sure how to proceed, so if someone could point me in the right direction, that'd be awesome! 

Ashley

**Comment by aralbright** [comment]
I decided to proceed with clustering, removing the mitochondrial and ribosomal genes beforehand. I then removed clusters that appeared to be grouped on high mitochondrial percentages, UMI counts, or gene counts. This was definitely a pretty stringent filtering, but that might just be necessary given the high background. 

Let me know if you have any other suggestions!

**Comment by sjfleming** [comment]
It does look like this is a bit of a difficult dataset, and I say that mainly because of the shape of the UMI curve

<img width="758" alt="image" src="https://user-images.githubusercontent.com/10214815/97353488-7e548380-186a-11eb-98f5-adcb5ccfa210.png">

It really does look like it's hard to make a determination of what's a cell by eye.  `remove-background` is almost surely overshooting here, and saying all droplets contain cells.

You can try to alleviate this by changing `--expected-cells` and `--total-droplets-included`, but I'm curious... how many cells do you expect here?  From looking at the UMI curve, it seems like there might be about 100 cells with UMI count > 1000.  Is that about right?

I might suggest trying 
`--expected-cells` 100
`--total-droplets-included` 4000
since I would guess that we're sure that everything after droplet 4000 is empty.  Right?

A dataset with so few cells is going to be a bit of a challenge.  Although the ambient RNA level (estimating from the UMI count per empty droplet) seems to be around 100, which is a bit high but not super high.  I think the problem here is that there are just so few cells.  Let me know if you agree...

**Comment by aralbright** [comment]
It's the opposite. I'm expecting a maximum of 10,000 cells, but with low expression that is likely very close to background levels. I have repeated the experiment recently so I'll have a biological replicate that may give me a bit of comfort if the outputs end up being roughly the same.

**Comment by sjfleming** [comment]
Did further datasets help make any more sense out of this situation?

**Comment by aralbright** [comment]
It's been a while, but if I'm remembering correctly I don't think so. I ended up having to figure something else out.
