### ISSUE TITLE
Different gene counts for cellbender and cellranger result

### ISSUE THREAD

**Issue by zhangzlab** [broadinstitute/CellBender#81]
Dear,
     Recently I found the raw gene counts from cellranger reuslt and cellbender result for the same cell is different, which may influence the MT gene percentage and further filtering threshold. Is it reasonable? I thought cellbender should only filter the empty dropout, why I got different gene expressions for the same cell?

**Comment by sjfleming** [comment]
Hi @zhangzlab ,

Yes, you should expect that the gene counts will change!  One function of the `remove-background` tool is to remove the empty droplets, like you said.

But the other main focus of the tool is to remove technical artifacts from the data, including ambient RNA and chimeric PCR amplification artifacts.  And when I say "remove artifacts" I mean "subtract counts" from the count matrix.

So `remove-background` will give you back a count matrix that has had some counts subtracted from the cells as well.  The idea is to remove counts that did not really originate in those cells, but ended up in the count matrix because of ambient RNA, etc.

You should find that the resulting count matrix is "cleaned up".  Check and see if your marker genes become more specific, or if differential expression signals become stronger.

See https://www.biorxiv.org/content/10.1101/791699v1 for details.

**Comment by sjfleming** [comment]
Of course, if you do not want the count matrix to change at all for some reason, but you do want to get rid of the empty droplets, you can use the output file called `_cell_barcodes.csv`, which has a list of all the non-empty droplet barcodes.  You can use those barcodes to take a subset of the original CellRanger count matrix, and work with that.

(Although I still recommend further cell quality control filtering, after CellBender.)

**Comment by zhangzlab** [comment]
Thanks, Stephen, that's helpful.
