### ISSUE TITLE
using multiple 10X runs to better estimate background and biological expression

### ISSUE THREAD

**Issue by vitkl** [broadinstitute/CellBender#89]
Hi CellBender team!

I am wondering if you have considered using multiple 10X runs to better estimate background and biological expression. The biological expression is shared between 10X runs whereas background, specifically the abundance of background counts, is different. Intuitively, assuming this distinction could help learn the background (because it changes) and will add more data for the estimation of biological expression (which autoencoders tend to benefit from). This assumption is also similar to TotalVI (https://github.com/YosefLab/scvi-tools/blob/master/scvi/model/totalvi.py). Does this make sense? Do you plan to implement something like this?

Thanks!

Vitalii

**Comment by sjfleming** [comment]
Hi Vitalii,

Thanks for the suggestion.  It is interesting...

Things I like about the idea: 
- You're right that the biological expression of cells is something we'd expect to be the same across samples (of course, ignoring batch effects...)
- The background for each experiment could be modeled separately
- The extra cells might help the auto encoder come up with a stronger prior on true biological expression

Potential cons that come to mind:
- Batch effects... I would think that we might have to tackle batch effects as scVI does in order to make use of the additional cells... because without any batch-effect correction, we will probably learn a batch-y latent space, which might be no better than running each experiment separately.  This makes it a much larger project in terms of scope.
- The big one in my mind: the output will depend on which experiments you analyze jointly.  This makes it very difficult to work on a big project where you might add extra samples later, etc.  The thing I like about the current one-sample analysis is that it's very modular.

But it's a very interesting idea... I will keep thinking about it!  Thanks!

**Comment by vitkl** [comment]
Thanks for giving some thought to this. With regard to cons:

1. With scVI having introduced support for Pyro, how hard would it be to replace your biological expression model with scVI model? Just a thought though - I am quite keen on writing models that are modular and can be easily combined.

2. What the potential failure points of CellBender V2 when applied to a single sample? If the V2 does not impute biological expression based on the autoencoder model then there is not much risk to having few cells in one-sample analysis and likely not much benefit to multi-sample analysis.

By the way, I really like the results of CellBender V2 (compared to V1 and SoupX) so would be great to see a more detailed description of the model.

**Comment by sjfleming** [comment]
Thanks!  We are in the process of writing up v2!  I am just going a bit slow :)
And I have a few changes coming up that will improve speed quite a bit.

1. As I understand it (but I will have to refresh my memory), scVI's model for biological expression is very similar to ours, at least in spirit.  Ours is just a variational autoencoder with one hidden layer.  Should be relatively easy to swap in different models, but I do believe the model in scVI is the same.
2. The distinction is that the _prior_ does impute biological expression based on an autoencoder model... but now in v2, the _posterior_ is different: the posterior makes use of the imputed (and smoothed) prior, but the (output) posterior itself is not an imputed thing.  It's more like solving a maximum likelihood estimation problem, given the data and the imputed prior.
