### ISSUE TITLE
use of jit

### ISSUE THREAD

**Issue by adamgayoso** [broadinstitute/CellBender#91]
Hello,

I see in your code that you've experimented with using JIT compiled modules. Do you find that this makes training much faster? On cpu/gpu?

**Comment by sjfleming** [comment]
Hi @adamgayoso !

I have played with JIT a little bit... but I have not tested it thoroughly.  Anecdotally, I will say that in this current Pyro framework I'm using, JIT (assuming I was using it correctly...) was not giving me big speedups on GPU.  Or any speedup at all, to be honest.  I did not check to see about a potential speedup on CPU, but this is a good idea... I mainly gave up on JIT because I wasn't seeing big speedups on GPU, which is my main intended use case.

I wonder... does that match your experience with scVI?
